	<div ui-view="" class="ui-view-main ng-scope"><!-- Fixed navbar -->
        <?php //include 'header.php';  ?>
        <section class="cover overlay height-70 height-270-xs"style="background-image: url('<?php echo asset_url()?>img/school/header-privacypolicy.jpg')">

            </section>
            <div class="container">
                <div class="row">
                    <section class="wrapper mtop2" id="privacy">
	<div>
	    <article class="col-l-16">
        <p>This document is an electronic record in terms of the Information Technology Act, 2000, and rules there under, as applicable, and the amended provisions pertaining to electronic
records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital
signatures.
		</p>
		<h4>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing
		    the rules and regulations, privacy policy and user agreement for access or usage of https://edbuddy.com
		</h4>
		<p>Welcome to Edbuddy.com! We are an Online Marketplace / Marketing and e­Advertising Platform connecting people in search of schools. Edbuddy.com and our subsidiaries and
			affiliates (collectively "Edbuddy.com") provide you with access to a variety of services, including but not limited to the www.edbuddy.com website (the "Website") and
			Edbuddy.com's mobile applications and all the products and services available through our website (collectively the "Services"). These Terms of Use govern access to and use of
			Edbuddy.com’s Services. This Website is owned and operated by M/s Locon Solutions Private Limited, a company incorporated under the Indian Companies Act, 1956, and having
			its principal place of business at 303, 3rd Floor, Supreme Business Park – A Wing, Hiranandani Garden, Powai, Mumbai 400076, Maharashtra, India.</p>

        <p>You are allowed to use our Services only if you can form a binding contract with us, and only in compliance with our Terms of Use and all applicable laws. The following terms and
			conditions apply to everyone who uses Edbuddy.com's Services (including school managements ), and they govern the relationship between Edbuddy.com and our users during their
			use of Edbuudy.com’s Services.</p>
        <p>Please read these Terms carefully before using our Services. By accessing and using our Services, you explicitly agree to comply with and be bound by our Terms of Use and Privacy
Policy.</p>
        <p><strong><u>Information You Provide to Us:</u></strong> The information we collect on or through our Services may include:<ul style="margin-left:20px;list-style-type:decimal !important"><li><strong>Your account information:</strong> Your full name, email address, postal code, password and other information you may provide with your account, such as your gender, mobile phone number and website. Your profile picture that will be publicly displayed as part of your account profile. You may optionally provide us with this information through third-party sign-in services such as Facebook and Google Plus. In such cases, we fetch and store whatever information is made available to us by you through these sign-in services.</li><li><strong>Your preferences:</strong> Your preferences and settings such as time zone and language.</li><li><strong>Your content:</strong> Information you provide through our Services, including your reviews, photographs, comments, lists, followers, the users you follow, current and prior restaurant reservation details, food ordering details and history, favorite restaurants, special restaurant requests, contact information of people you add to, or notify of, your restaurant reservations through our Services, names, and other information you provide on our Services, and other information in your account profile.</li><li><strong>Your searches and other activities:</strong> The search terms you have looked up and results you selected.</li><li><strong>Your browsing information:</strong> How long you used our Services and which features you used; the ads you clicked on.</li><li><strong>Your communications:</strong> Communications between you and other users or merchants through our Services; your participation in a survey, poll, sweepstakes, contest or promotion scheme; your request for certain features (e.g., newsletters, updates or other products); your communication with us about employment opportunities posted to the services.</li><li><strong>Your transactional information:</strong> If you make reservations or purchases through our Services, we may collect and store information about you to process your requests and automatically complete forms for future transactions, including (but not limited to) your phone number, address, email, billing information and credit or payment card information.  This information may be shared with third-parties which assist in processing and fulfilling your requests, including PCI compliant payment gateway processors. When you submit credit or payment card information, we encrypt the information using industry standard technologies, as further described below under "Payment Card Information."  If you write reviews about businesses with which you conduct transactions through our Services, we may publicly display information that you transacted with those businesses.</li><li><strong>Your Public Posts:</strong> You also may provide information (such as ratings, reviews, tips, photos, comments, likes, bookmarks, friends, lists, etc.) to be published or displayed (hereinafter, "<strong>posted</strong>") on publicly accessible areas of our Services, or transmitted to other users of our Services or third-parties (collectively, "<strong>User Contributions</strong>").  Your User Contributions are posted on and transmitted to others at your own risk.  Although we limit access to certain pages, you may set certain privacy settings for such information by logging into your account profile.  Please be aware that no security measures are perfect or impenetrable (see "Security" section below).  Additionally, we cannot control the actions of other users of our Services with whom you may choose to share your User Contributions.  Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons. We may display this information on the Services, share it with businesses, and further distribute it to a wider audience through third party sites and services. You should be careful about revealing any sensitive details about yourself in such postings.</li></ul></p>
</article>
	</div>
</section> 
                </div>
            </div>
    </div>
    <style>
/*         .form-control {
        width: 65%;
    }*/
        
    </style>
<script>
        
    </script>